---
# Install PostgreSQL on Enterprise Linux 6 (RHEL/CentOS/Scientific)
- hosts: postgres_servers
  sudo: yes
  sudo_user: root
  vars_files:
    - 'defaults/main.yml'
    - 'defaults/repo.yml'
  tasks:
    - include: 'tasks/main.yml'
